[package]
name = "bonding-curve-contract-meta"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@dharitri.com>"]
edition = "2021"
publish = false

[dependencies.bonding-curve-contract]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.16.0"
default-features = false
