[package]
name = "drt-game-sc"
version = "0.0.0"
authors = ["Mihai Calin Luca calin.luca@dharitri.com"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "1.16.0"

[dev-dependencies.dharitri-sc-scenario]
version = "1.16.0"
