[package]
name = "drt-game-sc"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.dharitri-sc]
version = "1.0.1"

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.1"
