[package]
name = "ping-pong-rewa"
version = "0.0.2"
authors = ["Bruda Claudiu-Marcel <claudiu725@yahoo.com>"]
edition = "2021"
publish = false

[lib]
path = "src/ping_pong.rs"

[dependencies.dharitri-sc]
version = "1.16.0"

[dev-dependencies.dharitri-sc-scenario]
version = "1.16.0"
