[package]
name = "dharitri-sc-price-aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.dharitri-sc-price-aggregator]
path = ".."

[dependencies.dharitri-sc]
version = "1.0.1"

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
