[package]
name = "check-pause-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Alin Cruceat <alin.cruceat@dharitri.com>"]

[dependencies.check-pause]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.16.0"
default-features = false
