[package]
name = "proxy-deployer-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["contact@dharitri.org"]

[dev-dependencies]

[dependencies.proxy-deployer]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
