[package]
name = "digital-cash"
version = "0.0.0"
authors = ["Valentin Craciun"]
edition = "2021"
publish = false

[lib]
path = "src/digital_cash.rs"

[dependencies.dharitri-sc]
version = "1.16.0"

[dev-dependencies.dharitri-sc-scenario]
version = "1.16.0"
