[package]
name = "pair-meta"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[dependencies.order-book-pair]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.16.0"
default-features = false
