[package]
name = "on-chain-claim-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = ["contact@dharitri.org"]

[dev-dependencies]

[dependencies.on-chain-claim]
path = ".."

[dependencies.dharitri-sc-meta-lib]
version = "1.0.1"
default-features = false
