[package]
name = "pair-mock"
version = "0.0.0"
authors = ["contact@dharitri.org"]
edition = "2021"
publish = false

[lib]
path = "src/pair_mock.rs"

[dependencies.dharitri-sc]
version = "1.0.1"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.dharitri-sc-scenario]
version = "1.0.1"
