name: On release, build contracts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: TerraDharitri/drt-sc-actions/.github/workflows/contracts.yml@v0.1.17
    with:
      image_tag: v8.0.1
      attach_to_existing_release: true
      package_whole_project_src: true
